<?php

use Opf\Registry\Registry;

?><!DOCTYPE html>
<html>
<head>
   <title>Welcome Page</title>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <!-- Latest compiled and minified CSS -->
   <link rel="stylesheet" href="../css/bootstrap.min.css">

   <!-- Optional theme -->
   <link rel="stylesheet" href="../css/bootstrap-theme.min.css">

   <!-- Latest compiled and minified JavaScript -->
   <script src="../js/jquery-2.0.3.min.js"></script>
   <script src="../js/bootstrap.min.js"></script>

   <link rel="stylesheet" href="../css/opf.css"/>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
   <div class="container">
      <div class="navbar-header">
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="/?app=home&cmd=main">OPF TestApp</a>
      </div>
      <div class="navbar-collapse collapse">
         <?php if(Registry::getInstance()->getSession()->getParameter('auth::signin') == true) { ?>
            <ul class="nav navbar-nav">
               <li class="active"><a href="/?app=secure&cmd=main">Home</a></li>
               <li><a href="/?app=secure&cmd=info">PHP Info</a></li>
            </ul>
            <a href="/?auth::logout" class="btn btn-default navbar-btn navbar-right">Sign out <?php echo Registry::getInstance()->getSession()->getParameter('auth::name') ?></a>
         <?php } else { ?>
            <ul class="nav navbar-nav">
               <li class="active"><a href="/?app=home&cmd=main">Home</a></li>
            </ul>
            <?php if($this->showLoginForm != true) { ?>
               <form class="navbar-form navbar-right" role="form" action="/?app=secure&cmd=main" method="post">
                  <div class="form-group">
                     <input type="text" placeholder="Email" class="form-control" name="<?php echo $this->fieldUser; ?>">
                  </div>
                  <div class="form-group">
                     <input type="password" placeholder="Password" class="form-control">
                  </div>
                  <button type="submit" class="btn btn-success">Sign in</button>
               </form>

            <?php }} ?>
      </div><!--/.navbar-collapse -->
   </div>
</div>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
   <div class="container">
      <h1>Hello, world!</h1>
      <p>This is a small demo to introduce you in OPF. With this demo application you have a fully working expample with following features:</p>
      <ul>
         <li>bootstraping your application</li>
         <li>working login system</li>
         <li>plugins</li>
         <li>templating</li>
         <li>controller</li>
      </ul>
      <p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>
   </div>
</div>

<div class="container">
   <!-- Example row of columns -->
   <div class="row">
      <div class="col-md-4">
         <h2>Getting started</h2>
         <p>A short overview about OPF, how to download and use it, basic configuration</p>
         <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      </div>

      <div class="col-md-4">
         <h2>Bootstrapping your Application</h2>
         <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
         <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      </div>

   </div>
   <hr/>
   <footer>
      <p>&copy; Oliver Feige 2014</p>
   </footer>

   <p class="bs-docs-debug">Logged in: <?php
      if(Registry::getInstance()->getSession()->getParameter('auth::signin') == true) {
         echo Registry::getInstance()->getSession()->getParameter('auth::name').' (<a href="/?auth::logout">logout</a>)';
      } else {
         echo 'not sign in';
      } ?>
      <br/><?php var_dump(Registry::getInstance()->getSession()); ?>
   </p>
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins)
<script src="https://code.jquery.com/jquery.js"></script> -->
</body>
</html>