<?php

use Opf\Registry\Registry;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="css/opf.css" rel="stylesheet" media="screen">

    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>

</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">

            <a class="brand" href="/">OPF simple test application</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li><a href="/">Home</a></li>
                    <li><a href="/?cmd=info">PHP Info</a></li>
                    <li><a href="/?cmd=signin">Sign In</a></li>
                    <li class="active"><a href="/?app=secure&cmd=info">Test to access secure content</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>

<div class="container">
    <h1>OPF simple test application</h1>
    <div><pre class="bs-docs-debug"><?php echo(Registry::getInstance()->getSession()); ?></pre></div>

</div>

</body>
</html>