<?php

use Opf\Registry\Registry;

?>
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Login</title>
   <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
   <style>
      body {
         padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
   </style>

</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
   <div class="navbar-inner">
      <div class="container">

         <a class="brand" href="/">OPF simple test application</a>
         <div class="nav-collapse collapse">
            <ul class="nav">
               <li class="active"><a href="/">Home</a></li>
               <li><a href="/?cmd=info">PHP Info</a></li>
               <li><a href="/?cmd=signin">Sign In</a></li>
               <li><a href="/?app=secure&cmd=info">Test to access secure content</a></li>
            </ul>
         </div><!--/.nav-collapse -->
      </div>
   </div>
</div>

<div class="container">
   <h1>OPF simple test application</h1>
   <form class="form-signin" method="post" action="<?php echo $this->action; ?>">
      <h2 class="form-signin-heading">Please sign in</h2>
      <input type="text" class="input-block-level" placeholder="Username"name="<?php echo $this->fieldUser; ?>" value="<?php echo $this->valueUser; ?>"/>
      <input type="password" class="input-block-level" placeholder="Password" name="<?php echo $this->fieldPassword; ?>"/>
      <button class="btn btn-large btn-primary" type="submit">Sign in</button>


      <fieldset>
         <legend>Session</legend>
         <?php var_dump(Registry::getInstance()->getSession()); ?>
      </fieldset>

      <p>Logged in: <?php
         if(Registry::getInstance()->getSession()->getParameter('auth::signin') == true) {
            echo Registry::getInstance()->getSession()->getParameter('auth::name').' (<a href="/?auth::logout">logout</a>)';
         } else {
            echo 'not sign in';
         } ?></p>
   </form>
</div>

</body>
</html>
