<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <title>Login</title>
</head>
<body>
<h1>Login</h1>
   <form method="post" action="<?php echo $this->action; ?>">
      <label for="<?php echo $this->fieldUser; ?>">Username</label><input name="<?php echo $this->fieldUser; ?>" value="<?php echo $this->valueUser; ?>"/>
      <label for="<?php echo $this->fieldPassword; ?>">Password</label><input name="<?php echo $this->fieldPassword; ?>"/>
      <input type="submit"/>
   </form>

</body>
</html>