<?php

use Opf\Registry\Registry;

?><!DOCTYPE html>
<html>
<head>
   <title>Welcome Page</title>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <!-- Latest compiled and minified CSS -->
   <link rel="stylesheet" href="../css/bootstrap.min.css">

   <!-- Optional theme -->
   <link rel="stylesheet" href="../css/bootstrap-theme.min.css">

   <!-- Latest compiled and minified JavaScript -->
   <script src="../js/jquery-2.0.3.min.js"></script>
   <script src="../js/bootstrap.min.js"></script>

   <link rel="stylesheet" href="../css/opf.css"/>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
   <div class="container">
      <div class="navbar-header">
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="/?app=home&cmd=main">OPF TestApp</a>
      </div>
      <div class="navbar-collapse collapse">
         <?php if(Registry::getInstance()->getSession()->getParameter('auth::signin') == true) { ?>
            <ul class="nav navbar-nav">
               <li class="active"><a href="/?app=secure&cmd=main">Home</a></li>
               <li><a href="/?app=secure&cmd=info">PHP Info</a></li>
            </ul>
            <a href="/?auth::logout" class="btn btn-default navbar-btn navbar-right">Sign out <?php echo Registry::getInstance()->getSession()->getParameter('auth::name') ?></a>
         <?php } else { ?>
            <ul class="nav navbar-nav">
               <li class="active"><a href="/?app=home&cmd=main">Home</a></li>
            </ul>
            <?php if($this->showLoginForm != true) { ?>
            <form class="navbar-form navbar-right" role="form" action="/?app=secure&cmd=main" method="post">
               <div class="form-group">
                  <input type="text" placeholder="Email" class="form-control" name="<?php echo $this->fieldUser; ?>">
               </div>
               <div class="form-group">
                  <input type="password" placeholder="Password" class="form-control">
               </div>
               <button type="submit" class="btn btn-success">Sign in</button>
            </form>

         <?php }} ?>
      </div><!--/.navbar-collapse -->
   </div>
</div>

<div class="container">

   <form class="form-signin" role="form" method="post" action="<?php echo $this->action; ?>">
      <h2 class="form-signin-heading">Please sign in</h2>
      <div class="form-group has-error">
         <label class="control-label" for="inputError">Username oder Passwort ist falsch</label>
         <input type="text" class="form-control" id="inputError" placeholder="Email address" required="required" autofocus="autofocus" name="<?php echo $this->fieldUser; ?>" value="<?php echo $this->valueUser; ?>"/>
         <input type="password" class="form-control" placeholder="Password" required="required" name="<?php echo $this->fieldPassword; ?>"/>
      </div>
      <label class="checkbox">
         <input type="checkbox" value="remember-me"/> Remember me
      </label>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
   </form>

   <p class="bs-docs-debug">Logged in: <?php
      if(Registry::getInstance()->getSession()->getParameter('auth::signin') == true) {
         echo Registry::getInstance()->getSession()->getParameter('auth::name').' (<a href="/?auth::logout">logout</a>)';
      } else {
         echo 'not sign in';
      } ?>
      <br/><?php var_dump(Registry::getInstance()->getSession()); ?>
   </p>

   <hr/>
   <footer>
      <p>&copy; Oliver Feige 2014</p>
   </footer>
</div>

</body>
</html>
