<?php

use Opf\Registry\Registry;

?><!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">

   <link rel="shortcut icon" href="/public/ico/favicon.png">

   <title>OPF - Home</title>

   <!-- Latest compiled and minified CSS -->
   <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">

   <!-- Optional theme -->
   <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">

   <!-- Latest compiled and minified JavaScript -->
   <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

   <!-- Custom styles for this template -->
   <link href="/css/opf.css" rel="stylesheet">

   <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
   <!--[if lt IE 9]>
   <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
   <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
   <![endif]-->
</head>

<body>

<div class="container">
   <div class="header">
      <ul class="nav nav-pills pull-right">
         <li class="active"><a href="">Home</a></li>
         <li><a href="/?cmd=signup">Sign-Up</a></li>
         <!--<li><a href="#">Contact</a></li>-->
      </ul>
      <h3 class="text-muted">OPF TestApp</h3>
   </div>

   <div class="container">

      <div class="jumbotron">
         <h1>OPF simple test application</h1>
         <p>this demo shows, how to create a simple sign in, and sign up</p>
         <p><a class="btn btn-lg btn-success" href="/?cmd=signup" role="button">Sign up today</a></p>
      </div>

   </div>

   <div class="row marketing">
      <div class="col-lg-6">
         <h4>Subheading</h4>
         <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

         <h4>Subheading</h4>
         <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

         <h4>Subheading</h4>
         <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
      </div>

      <div class="col-lg-6">
         <h4>Subheading</h4>
         <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

         <h4>Subheading</h4>
         <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

         <h4>Subheading</h4>
         <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
      </div>
   </div>

   <div class="footer">
      <p>&copy; Company 2013</p>
   </div>

</div> <!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
</body>
</html>





<!--
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">

            <a class="brand" href="/">OPF simple test application</a>

            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="active"><a href="/">Home</a></li>
                    <li><a href="/?cmd=info">PHP Info</a></li>
                    <li><a href="/?cmd=signin">Sign In</a></li>
                    <li><a href="/?app=secure&cmd=info">Test to access secure content</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>-->


